import type { ColoredPoint } from "./depth-points";

const VERTEX_BYTES = 15;

export function encodeBinaryPointCloudPly(points: ColoredPoint[]): Uint8Array {
  const header = new TextEncoder().encode([
    "ply",
    "format binary_little_endian 1.0",
    "comment generated by open-web-3d-capture",
    `element vertex ${points.length}`,
    "property float x",
    "property float y",
    "property float z",
    "property uchar red",
    "property uchar green",
    "property uchar blue",
    "end_header",
    "",
  ].join("\n"));
  const result = new Uint8Array(header.byteLength + points.length * VERTEX_BYTES);
  result.set(header);
  const view = new DataView(result.buffer);
  let offset = header.byteLength;
  for (const point of points) {
    view.setFloat32(offset, point.x, true);
    view.setFloat32(offset + 4, point.y, true);
    view.setFloat32(offset + 8, point.z, true);
    view.setUint8(offset + 12, clampColor(point.red));
    view.setUint8(offset + 13, clampColor(point.green));
    view.setUint8(offset + 14, clampColor(point.blue));
    offset += VERTEX_BYTES;
  }
  return result;
}

function clampColor(value: number): number {
  return Math.max(0, Math.min(255, Math.round(value)));
}
